### PR TITLE
revert libc removal

### PR DESCRIPTION
**Pull request by ordian**
cc https://github.com/paritytech/substrate/pull/4866

### CODE REVIEW

**Comment by dvdplm** [comment]
> Hold on, I will make few more benchmarks to be sure on this

Let us know what you find out. :)

**Comment by dvdplm** [comment]
Ping @NikVolf

**Comment by NikVolf** [comment]
Hey I am still not confident with numbers 

Is there any rush on this?

**Comment by dvdplm** [comment]
> Is there any rush on this?

No rush at all, take your time.

**Comment by NikVolf** [comment]
Seems it was false alarm from me in substrate.
More careful benchmarking with little variance reveals no difference.

**Comment by ordian** [comment]
Ok then, closing the PR as it makes no difference in parity-ethereum as well, although the pessimisation issue still holds https://github.com/rust-lang/rust/issues/69024.

**Pull request closed without merging**
