### PR TITLE
Fix `impl-serde::serializa/_raw` for empty slices

### PR DESCRIPTION
**Pull request by bkchr**
Fixes: https://github.com/paritytech/substrate/issues/3946

### CODE REVIEW

**Comment by tomusdrw** [comment]
What happened to the entire suite of tests for this stuff? Was it not ported from the ethereum codebase?

**Comment by ordian** [comment]
We have some tests in https://github.com/paritytech/parity-common/blob/master/ethereum-types/tests/serde.rs. I think it was ported from https://github.com/paritytech/primitives/, don't see any additional tests there.

**Comment by niklasad1** [comment]
@tomusdrw I think only `fixed_hash` and `uint` tests were ported to this repo but I'm not sure how they differ.

As I said before, `ethereum` doesn't use serialize/deserialize `Bytes` from this repo so definitely not ported from `ethereum` but we should merge them ideally

**Comment by dvdplm** [comment]
It's been a while but I don't think there were serde tests in `primitives`, or only very basic.

**Pull request merged**
