### PR TITLE
Fix fixed-hash

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

Fix the problem that the current version of  `fixed-hash` cannot be defined in constant directly.

related issue link: #109

### CODE REVIEW

**Comment by koushiro** [comment]
[clabot:check]

**Comment by Robbepop** [comment]
> Very much in favour of this. Without this change, the [`storage_keys!` macro](https://github.com/paritytech/pwasm-repo-contract/blob/master/contract/src/lib.rs) breaks.

Glad that you pointed this out!
However, on the other side the fix for `storage_keys` seems to be simple.

**Comment by larsrh** [comment]
The way I'm working around this right now looks as follows:

```rust
pub struct Key {
    pub key: [u8; 32]
}

impl Key {
    pub fn new(key: [u8; 32]) -> Key {
        Key { key: key }
    }

    pub fn h256(&self) -> H256 {
        H256::from(self.key)
    }
}

#[macro_export]
macro_rules! storage_keys {
	() => {};
	($($name:ident),*) => {
		storage_keys!(0u8, $($name),*);
	};
	($count:expr, $name:ident) => {
		static $name: Key = Key { key: [$count, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] };
	};
	($count:expr, $name:ident, $($tail:ident),*) => {
		static $name: Key = Key { key: [$count, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] };
		storage_keys!($count + 1u8, $($tail),*);
	};
}
```

Essentially, I'm building my own key type for storage.

**Comment by Robbepop** [comment]
I ll merge it as soon as CI is okay with it.

**Comment by bkchr** [comment]
@Robbepop travis windows is always broken and after they kicked out all people, it will probably never work.

**Pull request merged**
