### PR TITLE
Use 2018 edition for rustfmt

### LINKED ISSUE #264: Add edition 2018 to rustfmt.toml
The #143 issue is closed and all crates were migrated to 2018 edition, but the `rustfmt.toml` still checks/formats the code as 2015 edition.

There's a difference between `cargo fmt` & `rustfmt`:

```zsh
➜  fixed-hash git:(master) cargo fmt -- src/tests.rs
➜  fixed-hash git:(master) git diff
➜  fixed-hash git:(master) rustfmt src/tests.rs
➜  fixed-hash git:(master) ✗ git diff
diff --git a/fixed-hash/src/tests.rs b/fixed-hash/src/tests.rs
index c587281..f3fe1e1 100644
--- a/fixed-hash/src/tests.rs
+++ b/fixed-hash/src/tests.rs
@@ -232,7 +232,7 @@ mod from_low_u64 {
 #[cfg(feature = "rand")]
 mod rand {
 	use super::*;
-	use ::rand::{rngs::StdRng, SeedableRng};
+	use rand::{rngs::StdRng, SeedableRng};

 	#[test]
 	fn random() {
➜  fixed-hash git:(master) ✗
```

If your editor is configured to use `rustfmt` directly (mine is) then it reformats the code and it can break the code (it actually does break the `fixed-hash` crate).

The reason is that the `cargo fmt` checks `Cargo.toml:package:edition`, but `rustfmt` doesn't and it only checks `rustfmt.toml` file.

I'd suggest to:

* add `edition = "2018"` line to the `rustfmt.toml`
* add `cargo fmt -- --check` line to the `.travis.yml` to enforce formatting

No more breakage after this change:

```sh
➜  fixed-hash git:(master) print 'edition = "2018"' >> ../rustfmt.toml
➜  fixed-hash git:(master) ✗ rustfmt src/tests.rs
➜  fixed-hash git:(master) ✗ git diff src/tests.rs
➜  fixed-hash git:(master) ✗
```

I can create PR for this simple change, but not sure what is your opinion about enforced formatting (`cargo fmt -- --check` -> `.travis.yml`).

### PR DESCRIPTION
**Pull request by zrzka**
Not sure about adding `cargo fmt -- --check` to `.travis.yml` (see #264), keeping it out for now.

Fixes #264

### CODE REVIEW

**Comment by ordian** [comment]
@zrzka we already have https://github.com/paritytech/parity-common/blob/53678a194e3313c71cb00252deaf2769fa35c9e7/.travis.yml#L12
it doesn't seem to be enforced, let's fix that

**Comment by zrzka** [comment]
@ordian missed it. Travis CI:

> The exit code of `after_success`, `after_failure`, `after_script`, `after_deploy` and subsequent stages do not affect the build result. However, if one of these stages times out, the build is marked as failed.

I think it should be enough to change `after_script` to `script`.

**Comment by ordian** [comment]
please fix the formatting https://travis-ci.org/paritytech/parity-common/jobs/614448593#L217
also, are you sure that the `script` section in stable doesn't override the global script section? we want to run both

**Comment by zrzka** [comment]
> Also, are you sure that the script section in stable doesn't override the global script section? We want to run both on stable.

It does. I moved it to the global `script` section:

```yaml
script:
   - if [ "$TRAVIS_RUST_VERSION" == "stable" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then
     cargo fmt -- --check;
     fi
```

**Pull request merged**
