### PR TITLE
travis: pin geckodriver in wasm-pack tests

### PR DESCRIPTION
**Pull request by ordian**
https://github.com/rustwasm/wasm-pack/issues/891
https://github.com/rustwasm/wasm-bindgen/issues/2261

### CODE REVIEW

**Comment by ordian** [comment]
>  pin to geckodriver@1.19.1 which I assume uses geckodriver 0.26 under the hood somewhere

correct
>  I'm not sure what to make of the rest of the changes. How is this related to chromedriver which is now removed?

`chromedriver` is needed for `--chrome` tests, which we don't do anyway due to https://travis-ci.org/github/paritytech/parity-common/jobs/714472822#L2348 failing on Linux

**Comment by dvdplm** [comment]
> > I'm not sure what to make of the rest of the changes. How is this related to chromedriver which is now removed?
> 
> `chromedriver` is needed for `--chrome` tests, which we don't do anyway due to https://travis-ci.org/github/paritytech/parity-common/jobs/714472822#L2348 failing on Linux

I still don't get it, sorry! Did both chrome and gecko start to fail and with this PR we fix only gecko? Is there hope to fix chrome as well or are you saying it's impossible or not needed, or…?

**Comment by ordian** [comment]
> Did both chrome and gecko start to fail and with this PR we fix only gecko? Is there hope to fix chrome as well or are you saying it's impossible or not needed, or…?

I didn't delete `--chrome` flag in this PR, it wasn't present because it doesn't work and I don't have time to investigate why, so it is out of scope of this PR. This PR only fixes `--firefox` tests to make CI green. And removes currently unused dependencies.

**Comment by dvdplm** [comment]
> This PR only fixes `--firefox` tests to make CI green. And removes currently unused dependencies.


Now I finally get it. We have `cd kvdb-web/ && wasm-pack test --headless --firefox` but that broke with the latest release. We were installing chromedriver as well, but never had a `wasm-pack test --headless --chrome`?

Thanks.

**Comment by ordian** [comment]
> We have cd kvdb-web/ && wasm-pack test --headless --firefox but that broke with the latest release. We were installing chromedriver as well

exactly

> but never had a wasm-pack test --headless --chrome?

We used to have it until it started to fail: https://github.com/paritytech/parity-common/pull/324. PRs to bring it back are welcome of course ;)

**Pull request merged**
