### PR TITLE
Bump secp256k1 to 0.19, use global context

### PR DESCRIPTION
**Pull request by vorot93**

### CODE REVIEW

**Review by ordian — APPROVED** [review]

**Review by dvdplm — APPROVED** [review]

**Comment by dvdplm** [comment]
Needs `cargo fmt` run.

The test failure is actually relevant: all-zero messages are not invalid anymore. I think this is alright for ethereum but my memory is weak and I don't remember the details tbh.

**Comment by niklasad1** [comment]
> The test failure is actually relevant: all-zero messages are not invalid anymore. I think this is alright for ethereum but my memory is weak and I don't remember the details tbh.

https://github.com/rust-bitcoin/rust-secp256k1/pull/207 is included in this release. I think you are right. 

Do you remember the `ethereum builtin in bug` :)?

//cc @sorpaas I guess you're know this.

**Comment by ordian** [comment]
yeah, I think we should remove the failing test and `ZeroesAllowedMessage` or do you have another suggestion? :)

**Comment by niklasad1** [comment]
> yeah, I think we should remove the failing test and ZeroesAllowedMessage or do you have another suggestion? :)

No, I completely agree

**Comment by sorpaas** [comment]
@ordian @niklasad1 I'd propose we change this failing test to be "test zero message is valid".

I'll let the OpenEthereum people know about this just in case.

Also relevant rust-secp256k1 PR: https://github.com/rust-bitcoin/rust-secp256k1/pull/207

**Review by sorpaas — APPROVED** [review]

**Review by dvdplm — APPROVED** [review]
LGTM. Can you please add this to the `CHANGELOG` as a breaking change? :)

**Comment by vorot93** [comment]
@dvdplm done

**Comment by vorot93** [comment]
@dvdplm @ordian @sorpaas should be ready for merge

**Pull request merged**
