### PR TITLE
Ring 0.13

### PR DESCRIPTION
**Pull request by ordian**
cc https://github.com/paritytech/parity-ethereum/issues/9533

### CODE REVIEW

**Comment by ordian** [comment]
> BTW, have you tested it in party-ethereum including removing the patch for ring?

It doesn't work yet, this is blocked by https://github.com/ipld/rust-cid/pull/11.

**Comment by dvdplm** [comment]
With a minor version upgrade, I'm worried this might break consumers. Maybe better to go with a `0.2.0` version?

**Comment by ordian** [comment]
published: https://crates.io/crates/parity-crypto

**Comment by debris** [comment]
> yeah, although the interface didn't change, the new version won't build with other dependencies, which use ring 0.12

why?

**Comment by ordian** [comment]
> why?

https://github.com/briansmith/ring/blob/7e3682c02170f5eafa423b63bacfa018de2878a9/Cargo.toml#L14-L15

**Comment by c0gent** [comment]
Related issue: https://github.com/paritytech/parity-ethereum/issues/9533

@debris @ordian, most of the work required to update `parity-ethereum` to `ring 0.13` is here: https://github.com/poanetwork/parity-ethereum/tree/c0gent-tokio

Tests are broken and I haven't had time to look at it for a few days but I can spend time on it later this week. Should I go ahead submit a WIP PR?

**Pull request merged**
