### PR TITLE
Feature: Make U256::to_f64_lossy more accurate

### PR DESCRIPTION
**Pull request by junderw**
Based off of this blog post: https://blog.m-ou.se/floats/ (I tried to get the gist of this into the comments, but it's kind of long.)

This method of converting large unsigned integers into f64 is more accurate, but from my rough benchmarks, for most numbers there's at least a 3x slow down, and for some numbers (that work well with the simple method currently used) it's as much as a 10x slow down for speed.

Sacrificing speed for accuracy.

Please close if this is a trade off that's not acceptable.

I'd assume anyone dealing with floats is not expecting accuracy, but at the same time, I'm not too sure exactly *how* the current method's inaccuracies will manifest themselves.

Anywho, I was doing this work for another PR and thought it might be useful here.

### CODE REVIEW

**Comment by ggwpez** [comment]
>This method of converting large unsigned integers into f64 is more accurate, but from my rough benchmarks, for most numbers there's at least a 3x slow down, and for some numbers (that work well with the simple method currently used) it's as much as a 10x slow down for speed.

Thanks for mentioning this.  
We should probably add benchmarks here as well to compare. Anyway, i also think we should favour correctness.

**Review by ordian — APPROVED** [review]
Sorry for delay.

We're not using `fp-conversion` feature ourselves, so I won't be blocking the PR lacking knowledge of fp and the use-cases you're after. 

cc @bh2smith @fleupold who introduced this feature

**Comment by bh2smith** [comment]
Thanks for the ping @ordian -- I see that no tests have been changed and everything is passing, so I imagine the calculation has not changed so much in the end. Seems fine by me!

**Review by bh2smith — APPROVED** [review]

**Comment by ordian** [comment]
Hmm, actually I don't see CI checks running, maybe a fluke with GitHub CI.

**Comment by ordian** [comment]
@junderw  could you please merge recent master?

**Comment by junderw** [comment]
Rebased on master.

**Pull request merged**
