### PR TITLE
Upgrade zeroize version to v1.0

### PR DESCRIPTION
**Pull request by tarcieri**
v1.0 final release is out. Release notes:

https://github.com/iqlusioninc/crates/pull/279

### CODE REVIEW

**Comment by tarcieri** [comment]
[clabot:check].

**Comment by dvdplm** [comment]
@ordian time for a `0.4.3` release then right?

**Comment by ordian** [comment]
@tarcieri needs a merge with/rebase on master

@dvdplm I don't think it's time pressing, but sure, why not.

**Comment by ordian** [comment]
oh, actually, it's 1.0 on master already, but thanks anyway

**Comment by tarcieri** [comment]
Alrighty then!

**Pull request closed without merging**
