### PR TITLE
fixed-hash: remove `byteorder` feature

### PR DESCRIPTION
**Pull request by koushiro**
- remove `byteorder` feature
- rename `impl_ops_for_hash` => `impl_bit_ops_for_fixed_hash`
- remove `impl_cmp_for_fixed_hash` macro

### CODE REVIEW

**Comment by koushiro** [comment]
@ordian PTAL

**Review by ordian — APPROVED** [review]
the changes makes sense to me. unfortunately, they are semver breaking which will lead to version bump propagation everywhere

**Comment by koushiro** [comment]
> the changes makes sense to me. unfortunately, they are semver breaking which will lead to version bump propagation everywhere

I will submit a few more PRs after this, they will also result in breaking changes.

**Comment by ordian** [comment]
please also fix this: https://github.com/paritytech/parity-common/blob/366a95cdf1a10b4870b1d780f11748c76fecc4a8/.github/workflows/ci.yml#L70

**Comment by koushiro** [comment]
@bkchr PTAL

**Review by bkchr — APPROVED** [review]

**Pull request merged**
