### PR TITLE
parity-util-mem: use ios compilation conditions same as macos.

### LINKED ISSUE #521: [mem-util] reaching unreachable!(...) on iOS.
We've started getting an unreachable panic on iOS after adding parity-mem-util. The reason is the following code
https://github.com/paritytech/parity-common/blob/bb7b4376acea4f4cbc8e356d9b8e23de8502b293/parity-util-mem/src/allocators.rs#L110
Using the same compilation conditions as for macOS fixes the problem. I will open a PR.

### PR DESCRIPTION
**Pull request by artemii235**
Fixes #521

### CODE REVIEW

**Review by ordian — APPROVED** [review]
Thanks!

I don't know which allocator iOS uses by default and whether it's possible to use `jemalloc` [there](https://github.com/gnzlbg/jemallocator#platform-support).

It's fine to merge this if you tested it locally, however it would be hard for us to support iOS w/o proper CI setup for it.

**Comment by ordian** [comment]
(asking @cheme for a review because they implemented #93)

**Review by niklasad1 — APPROVED** [review]

**Comment by artemii235** [comment]
I guess I have to fix the formatting, I will push it asap.

**Review by cheme — APPROVED** [review]
LGTM, the cfg default to estimate heap size when we do not use jemalloc (so for mac and ios only option is jemalloc now, not sure if other allocator could make sense for those targets).

**Pull request merged**
