### PR TITLE
Make the HMAC conformant to RFC2104

### PR DESCRIPTION
**Pull request by tomaka**

### CODE REVIEW

**Comment by tomaka** [comment]
It would be a good idea to have more tests, and to compare the old ring-using implementation with the one from this PR. I clearly don't have the time to do that though.

**Comment by ordian** [comment]
I've mentioned in https://github.com/paritytech/parity-common/pull/139#issuecomment-491255380 there is a funtion https://docs.rs/hmac/0.7.0/hmac/trait.Mac.html#method.new_varkey that's supposed to do that.

**Comment by dvdplm** [comment]
I think this will "work", but it's odd that both `ring` ([here](https://github.com/briansmith/ring/blob/master/src/hmac.rs#L224-L229)) and `hmac` does the key stretching in a quite different way (and, importantly, in a way I do not understand the reason for).

**Comment by tomaka** [comment]
Could someone handle this instead of me?

**Comment by dvdplm** [comment]
> Could someone please handle this instead of me?

I'll do my very best.

**Pull request closed without merging**
