### PR TITLE
imp: in `fixed-hash` allow opting out `rand` when `std` enabled

### PR DESCRIPTION
**Pull request by Farhad-Shabani**
Closes: #805

### CODE REVIEW

**Review by ordian — APPROVED** [review]
This is a breaking change unfortunately.

We'd also need to bump MSRVRto 1.60 according to https://doc.rust-lang.org/cargo/reference/features.html#dependency-features:
> Note: The ? syntax is only available starting with Rust 1.60.

We don't have an automatic check for MSRV currently..

**Comment by dzmitry-lahoda** [comment]
@ordian what is next if you know?

think is that this thing (along with others) hampers adoption of non browser std wasm usage of these things. and before that was annoying in usage in pure parity codebase (that js compilation issue)

**Comment by ordian** [comment]
> @ordian what is next if you know?
> 
> think is that this thing (along with others) hampers adoption of non browser std wasm usage of these things. and before that was annoying in usage in pure parity codebase (that js compilation issue)

Tests are failing (exactly because this is a breaking change). They need to be fixed, then it can be merged and later released as a breaking change.

But I am not sure why you are blocked on this. I don't see any `std` gated code in this crate. Could you just disable std feature and add explicitly crate dependencies you need `std` features from (e.g. byteorder) with `std` feature enabled as a workaround?

**Comment by ordian** [comment]
Yeah, sometimes you can't control which features are selected due to transitive dependencies and cargo's feature unification.

**Comment by dzmitry-lahoda** [comment]
@Farhad-Shabani 

seems tests are failing

```
   Compiling bounded-collections v0.1.9 (/Users/runner/work/parity-common/parity-common/bounded-collections)
error[E0599]: no function or associated item named `random` found for struct `H256` in the current scope
Error:   --> kvdb-rocksdb/examples/memtest.rs:51:25
   |
51 |         Self::with_seed(H256::random())
   |                               ^^^^^^ function or associated item not found in `H256`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `kvdb-rocksdb` (example "memtest") due to previous error
Error: warning: build failed, waiting for other jobs to finish...
Error: The process '/Users/runner/.cargo/bin/cargo' failed with exit code 101
```

**Pull request merged**
