### PR TITLE
Use EntropyRng instead of OsRng

### PR DESCRIPTION
**Pull request by tomaka**
`EntropyRng` is also cryptographically secure, but will use jitter RNG (http://www.chronox.de/jent/doc/CPU-Jitter-NPTRNG.html) if the `OsRng` isn't available.

### CODE REVIEW

**Comment by tomaka** [comment]
The objective of this is https://github.com/paritytech/substrate/issues/2416

**Comment by ordian** [comment]
cc rust-random/rand/issues/760, rust-random/rand/pull/765,

**Comment by tomaka** [comment]
I suggest merging this anyway.
The reason for this PR is at the moment in `rand 0.6` the `OsRng` doesn't exist for WASM, which leads to the compilation failing.
Whatever changes the discussion in https://github.com/rust-random/rand/issues/760 refer to are, they will only land in rand 0.7, which needs to be manually put in parity-common.

**Comment by dvdplm** [comment]
@tomaka just to be sure I understand the intent here: `OsRng` does not compile to wasm; `JitterRng` does; switching to `EntropyRng` gets us the needed fallback when compiling for browsers. Correct?

What do you make of the issues @ordian mentions? Seems like `EntropyRng` is not getting removed in the short term, but will be eventually?

**Comment by dvdplm** [comment]
LGTM but I'll let @ordian press the green button here first.

**Comment by tomaka** [comment]
> @tomaka just to be sure I understand the intent here: OsRng does not compile to wasm; JitterRng does; switching to EntropyRng gets us the needed fallback when compiling for browsers. Correct?

Yes

**Comment by ordian** [comment]
I think one of the reasons `EntropyRng` was deprecated is security concerns (rust-random/rand/issues/699), but it seems like we don't have a better alternative for WASM, so I'll approve this PR.

**Comment by tomaka** [comment]
> security concerns (rust-random/rand/issues/699)

Oh, that's interesting. I had concerns as well, but considering that it was marked as `CryptoRng` I was assuming that they knew what they were doing. :sweat_smile:

**Comment by tomaka** [comment]
But as mentioned in https://github.com/rust-random/rand/issues/760, we can assume that the `OsRng` works everywhere and that the `JitterRng` will never be used except on WASM.

In other words, this PR is basically a quickfix while waiting for rand 0.7.

**Pull request merged**
