### PR TITLE
Fix removal of storage variable with fatdb.

### PR DESCRIPTION
**Pull request by cheme**
On https://github.com/paritytech/parity-ethereum/issues/9180 use of fatdb with an archive node leads to this situation : 
in a block :
- tr1 sstore 0 at address a delete is send to archivedb through fatdb
- tr2 sstore a val at same address an insert to archivedb through fatdb (the bug is that it is not the same address because delete do not use the right storing address) 
- tr3 sstore 0 again and a second delete is send to archive

(double delete at a address due to the intermediate insert done at another address -> break assertion of reference count max at 1 one an archive node).
So this fix fatdb to delete and insert at same address (I kept the scheme of double hashing because it is consistent with the fatdb query and existing test cases but I am not sure it is needed, if a reviewer can point out the need for this double hashing it interests me).

### CODE REVIEW

**Comment by dvdplm** [comment]
@rphmeier explained the double hashing but I've already forgotten what it was. :/ It is indeed needed though.

**Comment by cheme** [comment]
My first guess would be to get an uniform address space distribution (96 bits of hashdb key are not).

**Comment by cheme** [comment]
There is something tricky with this removal : in our use case (archivedb) we do not want it to actually happen except at a single block level (so we can query at previous block) and it will not due to archivedb implementation.
But if we run fatdb in non archive mode, this deletion may not be what we want and we may prefer to remove those deletion lines (we will get additional false value in the db but it is only an issue for the disk space). 
I am really not sure if using the fatdb without archive makes sense (`parity_listStorageKeys` seems to be the only method that is impacted by this suppression).
If it makes sense (non archive + fatdb), an alternate fix would be to avoid removing this association at all.

**Comment by dvdplm** [comment]
@cheme I agree that the current behaviour looks broken. I don't fully understand what the purpose of `FatDB` is but this test fails on master and passes on this branch (@ordian is this sort of what you were asking for?):

```rust
	#[test]
	fn insert_and_removal_leaves_the_db_empty() {
		use hashdb::HashDB;
		let mut db = MemoryDB::<KeccakHasher>::new();
		let mut root = H256::new();
		{
			let mut t = FatDBMut::new(&mut db, &mut root);
			t.insert(&[1], &[2]).unwrap();
			t.remove(&[1]).unwrap();
		}
		assert_eq!(db.keys().len(), 0);
	}
```

**Comment by ordian** [comment]
@dvdplm yes, a similar test was added already by @cheme.

**Comment by ordian** [comment]
@dvdplm should we publish `patricia-tree` `0.2.2` and update `parity-ethereum` and `substrate` as well?

**Comment by dvdplm** [comment]
> should we publish patricia-tree 0.2.2

Yes. I have pushed out [`0.2.2-beta.0`](https://crates.io/crates/patricia-trie/0.2.2-beta.0). When we feel confident that https://github.com/paritytech/parity-ethereum/issues/9213 is fixed we'll get it off the beta. In-progress PR [here](https://github.com/paritytech/parity-common/pull/52).

:)

**Pull request merged**
