### PR TITLE
Update rust-crypto dependency to RustCrypto project

### PR DESCRIPTION
**Pull request by cheme**
In this PR I got rid of the remaining uses of the rust-crypto crate, to use the corresponding RustCrypto ones.
One major difference is that I do not target aes-safe but the roots aes crates : if compiling with  `RUSTFLAGS='-C target-feature=+aes,+ssse3,+sse2'` the aesni implementation will be used (only for x86).
There is also two aes encoder/decoder struct which are basically here to get rid of rust-crypto in network-devp2p.

### CODE REVIEW

**Comment by cheme** [comment]
I agree with your first two points, this PR is mainly an update (RustCrypto is mainly rust-crypto with maintenance and some evo).

On the third point we can still use a similar interface as rust-crypto (I just change to avoid usage of two buffers so we would need to copy_from_slice too at some places), yet the stream interface leads to better results in my case (no need to adjust buffer size to a block length multiple). 

About the `copy_from_slice` it can be avoided by using the additional `inplace` function in parity-crypto and sometime avoid buffer allocation: eg https://github.com/paritytech/parity-ethereum/compare/master...cheme:RustCrypto#diff-ee20f8e316717999d2a4dee44afa6154
(it is a branch of parity-ethereum with all rust-crypto dependancies moved to parity-crypto but it uses the RustCrypto version of parity-crypto so I will probably not PR (I used it for my still syncing node with aes-ni activated and it may be a bit faster but I did not have metrics)).

As you asked I did a very quick bench : https://gist.github.com/cheme/2dcd97a7a08efc73027126f70fb3e64a

There is some small difference (I think instantiation may be a bit more costy with RustCrypto : for small content it is slower while for big content it is way faster).
But for nework-devp2p for instance it should be not that problematic because the encoder/decoder are stored and not instantiated for every operations.

I am keeping it for now (it was in libp2p that rust-crypto was a real issue : https://github.com/libp2p/rust-libp2p/issues/371 ), as it is not that big of an issue to drop it but other.

Also about the choice of a crypto crate, I do not believe there is a magic solution, yet I think that using standard traits could be a good thing (being able to switch crypto implementation easily, especially when targeting wasm or other less common targets).

**Comment by dvdplm** [comment]
> using standard traits could be a good thing

@cheme  I've seen this idea floating around in a few places and it sounds very enticing (especially being able to have a fully pluggable crypto backend so we can run tests against all backends) but I'm a bit hazy on the details of how this would work exactly. Do you have a clear picture of the set of traits we'd need? Maybe even an example? Would be curious to see it. :)

**Comment by cheme** [comment]
I think we should ask @tomaka about that (I believe there was some issues using it with libp2p use and we may want his feedback).

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ordian** [comment]
Superseded by #85.

**Pull request closed without merging**
