### PR TITLE
Fix impl-rlp for uint in primitive-types

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

It should be like 

https://github.com/paritytech/parity-common/blob/c64e1b52e67d8426c6f19242de4dea6ed63074c4/rlp/src/impls.rs#L259-L263

### CODE REVIEW

**Comment by ordian** [comment]
Nice find, @koushiro!

There is also [`impl_uint_rlp!(U64, 1);`](https://github.com/paritytech/parity-common/blob/c64e1b52e67d8426c6f19242de4dea6ed63074c4/ethereum-types/src/uint.rs#L5).

I wonder whether we should fix `impl_uint_rlp!` macro itself, since it's confusing that it accepts `size` as bytes, while `impl-serde` and `impl-codec` as 8-byte words. cc @sorpaas (I believe it was first implemented in #86?) and cc @Robbepop. Also we have both `ethereum` feature in `rlp` and `impl-rlp` feature in `primitive-types` (probably for historical reasons, but maybe we can sort out what depends on what now).

**Comment by koushiro** [comment]
> Nice find, @koushiro!
> 
> There is also [`impl_uint_rlp!(U64, 1);`](https://github.com/paritytech/parity-common/blob/c64e1b52e67d8426c6f19242de4dea6ed63074c4/ethereum-types/src/uint.rs#L5).
> 
> I wonder whether we should fix `impl_uint_rlp!` macro itself, since it's confusing that it accepts `size` as bytes, while `impl-serde` and `impl-codec` as 8-byte words. cc @sorpaas (I believe it was first implemented in #86?) and cc @Robbepop. Also we have both `ethereum` feature in `rlp` and `impl-rlp` feature in `primitive-types` (probably for historical reasons, but maybe we can sort out what depends on what now).

It seems that there is no `U64` type in `primitive-types`, and I have fixed the `impl_uint_rlp!` macro. PTAL, @ordian .

**Comment by koushiro** [comment]
> LGTM, but would be nice to have tests to catch that kind of bugs.
> 
> CI failure is unrelated (travis on Windows is broken for ages, I'll open a separate PR to migrate back to appveyor).

Maybe we could add some tests from https://github.com/chainx-org/chainx-common/blob/develop/primitive-types/src/tests.rs

**Comment by ordian** [comment]
Ok, let's merge this PR. A PR with tests is very welcome.

**Pull request merged**
